# Generated by Django 3.2.13 on 2022-11-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.IntegerField(blank=True, null=True, verbose_name='Регистрационный номер')),
                ('dateInput', models.DateField(blank=True, null=True, verbose_name='Дата поступления')),
                ('otKogo', models.CharField(blank=True, max_length=1000, null=True, verbose_name='От кого')),
                ('vxnumber', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Входящий номер')),
                ('isxnumber', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Исходящий номер')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Краткое содеражние')),
                ('executor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Исполнитель')),
                ('perfomance', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Отметка об исполнении')),
                ('control', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Признак контроля')),
                ('answertMail', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответ на письмо')),
                ('note', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Примечание')),
                ('nd', models.CharField(blank=True, choices=[('07-01', '07-01'), ('07-02', '07-02'), ('07-03', '07-03'), ('07-04', '07-04'), ('07-05', '07-05'), ('07-06', '07-06'), ('07-07', '07-07'), ('07-08', '07-08'), ('07-09', '07-09'), ('07-10', '07-10'), ('07-11', '07-11'), ('07-12', '07-12'), ('07-13', '07-13'), ('07-14', '07-14'), ('07-15', '07-15'), ('07-16', '07-16'), ('07-17', '07-17'), ('07-18', '07-18')], max_length=1000, null=True, verbose_name='Номенклатурное дело')),
            ],
        ),
    ]
